"""add_employee_work_schedule

Revision ID: 8bd9f32fe6ad
Revises: d6fb3ce23c45
Create Date: 2026-03-17 19:05:39.522210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bd9f32fe6ad'
down_revision: Union[str, None] = 'd6fb3ce23c45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('work_start_time', sa.Time(), nullable=True, comment="Xodimning shaxsiy kelish vaqti. None bo'lsa filial vaqti ishlatiladi"))
    op.add_column('employees', sa.Column('work_end_time', sa.Time(), nullable=True, comment="Xodimning shaxsiy ketish vaqti. None bo'lsa filial vaqti ishlatiladi"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'work_end_time')
    op.drop_column('employees', 'work_start_time')
    # ### end Alembic commands ###
