"""hr_v2_employee_branch

Revision ID: caae22fa19b8
Revises: 7a1e5d8b0e79
Create Date: 2026-03-12 06:37:23.486666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caae22fa19b8'
down_revision: Union[str, None] = '7a1e5d8b0e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
